apiVersion: apps/v1
kind: Deployment
metadata: 
    name: php-site-hml
spec:
    replicas: 2
    selector:
        matchLabels:
            app: php-site-hml
    template:
        metadata:
            labels:
                app: php-site-hml
        spec:
            containers:
                - name: php-site-hml
                  image: hubdino/php-apache:1.1
                  ports:
                    - containerPort: 80
                  imagePullPolicy: IfNotPresent




