#FROM php:7.2-apache
FROM hubdino/php-apache:1.0

#COPY ./php.ini $PHP_INI_DIR/
ADD ./src-php /var/www/html

RUN apt-get update && apt-get install -y \
	vim \
	libxml2-dev \
	&& rm -rf /etc/apt/preferences.d/no-debian-php
RUN docker-php-ext-install soap
RUN a2enmod rewrite
RUN apt-get install -y php-soap
