apiVersion: v1
kind: Service
metadata:
    name: php-site-prd
    labels:
        app: php-site-prd
spec:
    type: NodePort    
    ports:
    - port: 8081
      targetPort: 80
      nodePort: 31200
    selector:
      app: php-site-prd
        

              