apiVersion: v1
kind: Service
metadata:
    name: php-site-hml
    labels:
        app: php-site-hml
spec:
    type: NodePort
    ports:
    - port: 8080
      targetPort: 80
      nodePort: 31100
    selector:
      app: php-site-hml
 