baseURL = "/"
languageCode = "en-us"
title = "Restauração IBS"
theme = "minimal"
relativeURLs = true
uglyURLs = true
disqusShortname = "" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Natan Dias"
    description = ""
    githubUsername = ""
    accent = "blue"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/fotos/"
    name = "Fotos"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "envelope-o"
    weight = 1
