apiVersion: v1
kind: Namespace
metadata:
  name: ktools
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ktools
  namespace: ktools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ktools
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: ktools
  namespace: ktools
---
apiVersion: v1
kind: Pod
metadata:
  name: ktools
  namespace: ktools
spec:
  serviceAccountName: ktools
  containers:
  - name: kube-tools
    image: natandias1/kube-tools:0.1
    imagePullPolicy: Always
    stdin: true
    tty: true
    env:
    - name: HOSTIP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP