baseurl = "/"
languageCode = "en-us"
theme = "hello-friend"
relativeURLs = true
uglyURLs = true

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Metadata mostly used in document's head
  description = "Emotions Homepage"
  keywords = "homepage, blog, games, development, programming"
  images = [""]

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "content/devlog"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

# Social icons
  [[params.social]]
    name = "youtube"
    url  = "https://www.youtube.com/channel/UCLFVeJNoZgIbIShtiPIE4xw"
  
  [[params.social]]
    name = "email"
    url  = "mailto:hubdinobr@gmail.com"
  

[languages]
  [languages.en]
    title = "Emotions Dev Page"
    subtitle = "Devlogs e Updates"
    keywords = ""
    copyright = ""
    readOtherPosts = "Leia mais..."

    [languages.en.params.logo]
      logoText = "cd /home/"
      logoHomeLink = "/index.html"
      #path ="/images/game_icon.png"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

	# You can create a language based menu
 

# And you can even create generic menu
[menu]

  [[menu.main]]
    identifier = "download"
    name       = "Play Store"
    url        = "https://play.google.com/store/apps/details?id=org.godotengine.emotions"
  
  [[menu.main]]
    identifier = "apoiase"
    name = "Apoia-se"
    url = "https://apoia.se/hubdinogames"
